// Code generated by "stringer -type=DomainSnapshotCreateFlags,DomainSnapshotDeleteFlags,DomainSnapshotListFlags,DomainSnapshotRevertFlags -output domainsnapshot_string.go"; DO NOT EDIT.

package libvirt

import "fmt"

const (
	_DomainSnapshotCreateFlags_name_0 = "DomainSnapshotCreateFlagRedefineDomainSnapshotCreateFlagCreateCurrent"
	_DomainSnapshotCreateFlags_name_1 = "DomainSnapshotCreateFlagNoMetadata"
	_DomainSnapshotCreateFlags_name_2 = "DomainSnapshotCreateFlagCreateHalt"
	_DomainSnapshotCreateFlags_name_3 = "DomainSnapshotCreateFlagCreateDiskOnly"
	_DomainSnapshotCreateFlags_name_4 = "DomainSnapshotCreateFlagCreateReuseExt"
	_DomainSnapshotCreateFlags_name_5 = "DomainSnapshotCreateFlagCreateQuiesce"
	_DomainSnapshotCreateFlags_name_6 = "DomainSnapshotCreateFlagCreateAtomic"
	_DomainSnapshotCreateFlags_name_7 = "DomainSnapshotCreateFlagCreateLive"
)

var (
	_DomainSnapshotCreateFlags_index_0 = [...]uint8{0, 32, 69}
	_DomainSnapshotCreateFlags_index_1 = [...]uint8{0, 34}
	_DomainSnapshotCreateFlags_index_2 = [...]uint8{0, 34}
	_DomainSnapshotCreateFlags_index_3 = [...]uint8{0, 38}
	_DomainSnapshotCreateFlags_index_4 = [...]uint8{0, 38}
	_DomainSnapshotCreateFlags_index_5 = [...]uint8{0, 37}
	_DomainSnapshotCreateFlags_index_6 = [...]uint8{0, 36}
	_DomainSnapshotCreateFlags_index_7 = [...]uint8{0, 34}
)

func (i DomainSnapshotCreateFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _DomainSnapshotCreateFlags_name_0[_DomainSnapshotCreateFlags_index_0[i]:_DomainSnapshotCreateFlags_index_0[i+1]]
	case i == 4:
		return _DomainSnapshotCreateFlags_name_1
	case i == 8:
		return _DomainSnapshotCreateFlags_name_2
	case i == 16:
		return _DomainSnapshotCreateFlags_name_3
	case i == 32:
		return _DomainSnapshotCreateFlags_name_4
	case i == 64:
		return _DomainSnapshotCreateFlags_name_5
	case i == 128:
		return _DomainSnapshotCreateFlags_name_6
	case i == 256:
		return _DomainSnapshotCreateFlags_name_7
	default:
		return fmt.Sprintf("DomainSnapshotCreateFlags(%d)", i)
	}
}

const (
	_DomainSnapshotDeleteFlags_name_0 = "DomainSnapshotDeleteFlagChildrenDomainSnapshotDeleteFlagMetadataOnly"
	_DomainSnapshotDeleteFlags_name_1 = "DomainSnapshotDeleteFlagChildrenOnly"
)

var (
	_DomainSnapshotDeleteFlags_index_0 = [...]uint8{0, 32, 68}
	_DomainSnapshotDeleteFlags_index_1 = [...]uint8{0, 36}
)

func (i DomainSnapshotDeleteFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _DomainSnapshotDeleteFlags_name_0[_DomainSnapshotDeleteFlags_index_0[i]:_DomainSnapshotDeleteFlags_index_0[i+1]]
	case i == 4:
		return _DomainSnapshotDeleteFlags_name_1
	default:
		return fmt.Sprintf("DomainSnapshotDeleteFlags(%d)", i)
	}
}

const (
	_DomainSnapshotListFlags_name_0 = "DomainSnapshotListFlagDescendantsDomainSnapshotListFlagRoots"
	_DomainSnapshotListFlags_name_1 = "DomainSnapshotListFlagMetadata"
	_DomainSnapshotListFlags_name_2 = "DomainSnapshotListFlagLeaves"
	_DomainSnapshotListFlags_name_3 = "DomainSnapshotListFlagNoLeaves"
	_DomainSnapshotListFlags_name_4 = "DomainSnapshotListFlagNoMetadata"
	_DomainSnapshotListFlags_name_5 = "DomainSnapshotListFlagInactive"
	_DomainSnapshotListFlags_name_6 = "DomainSnapshotListFlagAactive"
	_DomainSnapshotListFlags_name_7 = "DomainSnapshotListFlagDiskOnly"
	_DomainSnapshotListFlags_name_8 = "DomainSnapshotListFlagInternal"
	_DomainSnapshotListFlags_name_9 = "DomainSnapshotListFlagExternal"
)

var (
	_DomainSnapshotListFlags_index_0 = [...]uint8{0, 33, 60}
	_DomainSnapshotListFlags_index_1 = [...]uint8{0, 30}
	_DomainSnapshotListFlags_index_2 = [...]uint8{0, 28}
	_DomainSnapshotListFlags_index_3 = [...]uint8{0, 30}
	_DomainSnapshotListFlags_index_4 = [...]uint8{0, 32}
	_DomainSnapshotListFlags_index_5 = [...]uint8{0, 30}
	_DomainSnapshotListFlags_index_6 = [...]uint8{0, 29}
	_DomainSnapshotListFlags_index_7 = [...]uint8{0, 30}
	_DomainSnapshotListFlags_index_8 = [...]uint8{0, 30}
	_DomainSnapshotListFlags_index_9 = [...]uint8{0, 30}
)

func (i DomainSnapshotListFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _DomainSnapshotListFlags_name_0[_DomainSnapshotListFlags_index_0[i]:_DomainSnapshotListFlags_index_0[i+1]]
	case i == 4:
		return _DomainSnapshotListFlags_name_1
	case i == 8:
		return _DomainSnapshotListFlags_name_2
	case i == 16:
		return _DomainSnapshotListFlags_name_3
	case i == 32:
		return _DomainSnapshotListFlags_name_4
	case i == 64:
		return _DomainSnapshotListFlags_name_5
	case i == 128:
		return _DomainSnapshotListFlags_name_6
	case i == 256:
		return _DomainSnapshotListFlags_name_7
	case i == 512:
		return _DomainSnapshotListFlags_name_8
	case i == 1024:
		return _DomainSnapshotListFlags_name_9
	default:
		return fmt.Sprintf("DomainSnapshotListFlags(%d)", i)
	}
}

const (
	_DomainSnapshotRevertFlags_name_0 = "DomainSnapshotRevertFlagRunningDomainSnapshotRevertFlagPaused"
	_DomainSnapshotRevertFlags_name_1 = "DomainSnapshotRevertFlagForce"
)

var (
	_DomainSnapshotRevertFlags_index_0 = [...]uint8{0, 31, 61}
	_DomainSnapshotRevertFlags_index_1 = [...]uint8{0, 29}
)

func (i DomainSnapshotRevertFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _DomainSnapshotRevertFlags_name_0[_DomainSnapshotRevertFlags_index_0[i]:_DomainSnapshotRevertFlags_index_0[i+1]]
	case i == 4:
		return _DomainSnapshotRevertFlags_name_1
	default:
		return fmt.Sprintf("DomainSnapshotRevertFlags(%d)", i)
	}
}
