// Code generated by "stringer -type=DomainBlockResizeFlags,DomainXMLFlags,DomainCreateFlags,DomainRebootFlags,DomainShutdownFlags,DomainMigrateFlags,DomainUndefineFlags,DomainDefineXMLFlags,DomainDestroyFlags -output domain_string.go"; DO NOT EDIT.

package libvirt

import "fmt"

const _DomainBlockResizeFlags_name = "DomainBlockResizeFlagNoneDomainBlockResizeFlagBytes"

var _DomainBlockResizeFlags_index = [...]uint8{0, 25, 51}

func (i DomainBlockResizeFlags) String() string {
	if i >= DomainBlockResizeFlags(len(_DomainBlockResizeFlags_index)-1) {
		return fmt.Sprintf("DomainBlockResizeFlags(%d)", i)
	}
	return _DomainBlockResizeFlags_name[_DomainBlockResizeFlags_index[i]:_DomainBlockResizeFlags_index[i+1]]
}

const (
	_DomainXMLFlags_name_0 = "DomainXMLFlagSecureDomainXMLFlagInactive"
	_DomainXMLFlags_name_1 = "DomainXMLFlagUpdateCPU"
	_DomainXMLFlags_name_2 = "DomainXMLFlagMigratable"
)

var (
	_DomainXMLFlags_index_0 = [...]uint8{0, 19, 40}
	_DomainXMLFlags_index_1 = [...]uint8{0, 22}
	_DomainXMLFlags_index_2 = [...]uint8{0, 23}
)

func (i DomainXMLFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _DomainXMLFlags_name_0[_DomainXMLFlags_index_0[i]:_DomainXMLFlags_index_0[i+1]]
	case i == 4:
		return _DomainXMLFlags_name_1
	case i == 8:
		return _DomainXMLFlags_name_2
	default:
		return fmt.Sprintf("DomainXMLFlags(%d)", i)
	}
}

const (
	_DomainCreateFlags_name_0 = "DomainCreateFlagNoneDomainCreateFlagPausedDomainCreateFlagAutoDestroy"
	_DomainCreateFlags_name_1 = "DomainCreateFlagBypassCache"
	_DomainCreateFlags_name_2 = "DomainCreateFlagStartForceBoot"
	_DomainCreateFlags_name_3 = "DomainCreateFlagStartValidate"
)

var (
	_DomainCreateFlags_index_0 = [...]uint8{0, 20, 42, 69}
	_DomainCreateFlags_index_1 = [...]uint8{0, 27}
	_DomainCreateFlags_index_2 = [...]uint8{0, 30}
	_DomainCreateFlags_index_3 = [...]uint8{0, 29}
)

func (i DomainCreateFlags) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _DomainCreateFlags_name_0[_DomainCreateFlags_index_0[i]:_DomainCreateFlags_index_0[i+1]]
	case i == 4:
		return _DomainCreateFlags_name_1
	case i == 8:
		return _DomainCreateFlags_name_2
	case i == 16:
		return _DomainCreateFlags_name_3
	default:
		return fmt.Sprintf("DomainCreateFlags(%d)", i)
	}
}

const (
	_DomainRebootFlags_name_0 = "DomainRebootFlagDefaultDomainRebootFlagACPIDomainRebootFlagGuestAgent"
	_DomainRebootFlags_name_1 = "DomainRebootFlagInitctl"
	_DomainRebootFlags_name_2 = "DomainRebootFlagSignal"
	_DomainRebootFlags_name_3 = "DomainRebootFlagParavirt"
)

var (
	_DomainRebootFlags_index_0 = [...]uint8{0, 23, 43, 69}
	_DomainRebootFlags_index_1 = [...]uint8{0, 23}
	_DomainRebootFlags_index_2 = [...]uint8{0, 22}
	_DomainRebootFlags_index_3 = [...]uint8{0, 24}
)

func (i DomainRebootFlags) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _DomainRebootFlags_name_0[_DomainRebootFlags_index_0[i]:_DomainRebootFlags_index_0[i+1]]
	case i == 4:
		return _DomainRebootFlags_name_1
	case i == 8:
		return _DomainRebootFlags_name_2
	case i == 16:
		return _DomainRebootFlags_name_3
	default:
		return fmt.Sprintf("DomainRebootFlags(%d)", i)
	}
}

const (
	_DomainShutdownFlags_name_0 = "DomainShutdownFlagDefaultDomainShutdownFlagACPIDomainShutdownFlagGuestAgent"
	_DomainShutdownFlags_name_1 = "DomainShutdownFlagInitctl"
	_DomainShutdownFlags_name_2 = "DomainShutdownFlagSignal"
	_DomainShutdownFlags_name_3 = "DomainShutdownFlagParavirt"
)

var (
	_DomainShutdownFlags_index_0 = [...]uint8{0, 25, 47, 75}
	_DomainShutdownFlags_index_1 = [...]uint8{0, 25}
	_DomainShutdownFlags_index_2 = [...]uint8{0, 24}
	_DomainShutdownFlags_index_3 = [...]uint8{0, 26}
)

func (i DomainShutdownFlags) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _DomainShutdownFlags_name_0[_DomainShutdownFlags_index_0[i]:_DomainShutdownFlags_index_0[i+1]]
	case i == 4:
		return _DomainShutdownFlags_name_1
	case i == 8:
		return _DomainShutdownFlags_name_2
	case i == 16:
		return _DomainShutdownFlags_name_3
	default:
		return fmt.Sprintf("DomainShutdownFlags(%d)", i)
	}
}

const _DomainMigrateFlags_name = "DomainMigrateFlagLiveDomainMigrateFlagPeerToPeerDomainMigrateFlagTunneledDomainMigrateFlagPersistDestinationDomainMigrateFlagUndefineSourceDomainMigrateFlagPausedDomainMigrateFlagNonSharedDiskDomainMigrateFlagNonSharedIncrementalDomainMigrateFlagChangeProtectionDomainMigrateFlagUnsafeDomainMigrateFlagOfflineDomainMigrateFlagCompressedDomainMigrateFlagAbortOnErrorDomainMigrateFlagAutoConvergeDomainMigrateFlagRDMAPinAll"

var _DomainMigrateFlags_map = map[DomainMigrateFlags]string{
	1:     _DomainMigrateFlags_name[0:21],
	2:     _DomainMigrateFlags_name[21:48],
	4:     _DomainMigrateFlags_name[48:73],
	8:     _DomainMigrateFlags_name[73:108],
	16:    _DomainMigrateFlags_name[108:139],
	32:    _DomainMigrateFlags_name[139:162],
	64:    _DomainMigrateFlags_name[162:192],
	128:   _DomainMigrateFlags_name[192:229],
	256:   _DomainMigrateFlags_name[229:262],
	512:   _DomainMigrateFlags_name[262:285],
	1024:  _DomainMigrateFlags_name[285:309],
	2048:  _DomainMigrateFlags_name[309:336],
	4096:  _DomainMigrateFlags_name[336:365],
	8192:  _DomainMigrateFlags_name[365:394],
	16384: _DomainMigrateFlags_name[394:421],
}

func (i DomainMigrateFlags) String() string {
	if str, ok := _DomainMigrateFlags_map[i]; ok {
		return str
	}
	return fmt.Sprintf("DomainMigrateFlags(%d)", i)
}

const (
	_DomainUndefineFlags_name_0 = "DomainUndefineFlagManagedSaveDomainUndefineFlagSnapshotsMetadata"
	_DomainUndefineFlags_name_1 = "DomainUndefineFlagNVRAM"
)

var (
	_DomainUndefineFlags_index_0 = [...]uint8{0, 29, 64}
	_DomainUndefineFlags_index_1 = [...]uint8{0, 23}
)

func (i DomainUndefineFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _DomainUndefineFlags_name_0[_DomainUndefineFlags_index_0[i]:_DomainUndefineFlags_index_0[i+1]]
	case i == 4:
		return _DomainUndefineFlags_name_1
	default:
		return fmt.Sprintf("DomainUndefineFlags(%d)", i)
	}
}

const _DomainDefineXMLFlags_name = "DefineValidate"

var _DomainDefineXMLFlags_index = [...]uint8{0, 14}

func (i DomainDefineXMLFlags) String() string {
	i -= 1
	if i >= DomainDefineXMLFlags(len(_DomainDefineXMLFlags_index)-1) {
		return fmt.Sprintf("DomainDefineXMLFlags(%d)", i+1)
	}
	return _DomainDefineXMLFlags_name[_DomainDefineXMLFlags_index[i]:_DomainDefineXMLFlags_index[i+1]]
}

const _DomainDestroyFlags_name = "DestroyFlagDefaultDestroyFlagGraceful"

var _DomainDestroyFlags_index = [...]uint8{0, 18, 37}

func (i DomainDestroyFlags) String() string {
	i -= 1
	if i >= DomainDestroyFlags(len(_DomainDestroyFlags_index)-1) {
		return fmt.Sprintf("DomainDestroyFlags(%d)", i+1)
	}
	return _DomainDestroyFlags_name[_DomainDestroyFlags_index[i]:_DomainDestroyFlags_index[i+1]]
}
