// Code generated by "stringer -type=MessageStatus"; DO NOT EDIT.

package libvirt

import "fmt"

const _MessageStatus_name = "MessageStatusOKMessageStatusErrorMessageStatusContinue"

var _MessageStatus_index = [...]uint8{0, 15, 33, 54}

func (i MessageStatus) String() string {
	if i >= MessageStatus(len(_MessageStatus_index)-1) {
		return fmt.Sprintf("MessageStatus(%d)", i)
	}
	return _MessageStatus_name[_MessageStatus_index[i]:_MessageStatus_index[i+1]]
}
