// Code generated by "stringer -type=StoragePoolsFlags -output storagepool_string.go"; DO NOT EDIT.

package libvirt

import "fmt"

const _StoragePoolsFlags_name = "StoragePoolsFlagInactiveStoragePoolsFlagActiveStoragePoolsFlagPersistentStoragePoolsFlagTransientStoragePoolsFlagAutostartStoragePoolsFlagNoAutostartStoragePoolsFlagDirStoragePoolsFlagFSStoragePoolsFlagNETFSStoragePoolsFlagLogicalStoragePoolsFlagDiskStoragePoolsFlagISCSIStoragePoolsFlagSCSIStoragePoolsFlagMPATHStoragePoolsFlagRBDStoragePoolsFlagSheepdogStoragePoolsFlagGlusterStoragePoolsFlagZFS"

var _StoragePoolsFlags_map = map[StoragePoolsFlags]string{
	1:      _StoragePoolsFlags_name[0:24],
	2:      _StoragePoolsFlags_name[24:46],
	4:      _StoragePoolsFlags_name[46:72],
	8:      _StoragePoolsFlags_name[72:97],
	16:     _StoragePoolsFlags_name[97:122],
	32:     _StoragePoolsFlags_name[122:149],
	64:     _StoragePoolsFlags_name[149:168],
	128:    _StoragePoolsFlags_name[168:186],
	256:    _StoragePoolsFlags_name[186:207],
	512:    _StoragePoolsFlags_name[207:230],
	1024:   _StoragePoolsFlags_name[230:250],
	2048:   _StoragePoolsFlags_name[250:271],
	4096:   _StoragePoolsFlags_name[271:291],
	8192:   _StoragePoolsFlags_name[291:312],
	16384:  _StoragePoolsFlags_name[312:331],
	32768:  _StoragePoolsFlags_name[331:355],
	65536:  _StoragePoolsFlags_name[355:378],
	131072: _StoragePoolsFlags_name[378:397],
}

func (i StoragePoolsFlags) String() string {
	if str, ok := _StoragePoolsFlags_map[i]; ok {
		return str
	}
	return fmt.Sprintf("StoragePoolsFlags(%d)", i)
}
