// Code generated by "stringer -type=StorageVolumeDownloadFlags,StorageVolumeUploadFlags,StorageVolumeCreateFlags,StorageVolumeDeleteFlags,StorageVolumeResizeFlags,StorageVolumeWipeAlgFlags -output storagevolume_string.go"; DO NOT EDIT.

package libvirt

import "fmt"

const (
	_StorageVolumeDownloadFlags_name_0 = "StorageVolumeDownloadFlagNone"
	_StorageVolumeDownloadFlags_name_1 = "StorageVolumeDownloadFlagSparseStream"
)

var (
	_StorageVolumeDownloadFlags_index_0 = [...]uint8{0, 29}
	_StorageVolumeDownloadFlags_index_1 = [...]uint8{0, 37}
)

func (i StorageVolumeDownloadFlags) String() string {
	switch {
	case i == 0:
		return _StorageVolumeDownloadFlags_name_0
	case i == 2:
		return _StorageVolumeDownloadFlags_name_1
	default:
		return fmt.Sprintf("StorageVolumeDownloadFlags(%d)", i)
	}
}

const (
	_StorageVolumeUploadFlags_name_0 = "StorageVolumeUploadFlagNone"
	_StorageVolumeUploadFlags_name_1 = "StorageVolumeUploadFlagSparseStream"
)

var (
	_StorageVolumeUploadFlags_index_0 = [...]uint8{0, 27}
	_StorageVolumeUploadFlags_index_1 = [...]uint8{0, 35}
)

func (i StorageVolumeUploadFlags) String() string {
	switch {
	case i == 0:
		return _StorageVolumeUploadFlags_name_0
	case i == 2:
		return _StorageVolumeUploadFlags_name_1
	default:
		return fmt.Sprintf("StorageVolumeUploadFlags(%d)", i)
	}
}

const _StorageVolumeCreateFlags_name = "StorageVolumeCreateFlagNoneStorageVolumeCreateFlagPreallocMetadataStorageVolumeCreateFlagReflink"

var _StorageVolumeCreateFlags_index = [...]uint8{0, 27, 66, 96}

func (i StorageVolumeCreateFlags) String() string {
	if i >= StorageVolumeCreateFlags(len(_StorageVolumeCreateFlags_index)-1) {
		return fmt.Sprintf("StorageVolumeCreateFlags(%d)", i)
	}
	return _StorageVolumeCreateFlags_name[_StorageVolumeCreateFlags_index[i]:_StorageVolumeCreateFlags_index[i+1]]
}

const _StorageVolumeDeleteFlags_name = "StorageVolumeDeleteFlagNormalStorageVolumeDeleteFlagZeroesStorageVolumeDeleteFlagWithSnapshots"

var _StorageVolumeDeleteFlags_index = [...]uint8{0, 29, 58, 94}

func (i StorageVolumeDeleteFlags) String() string {
	if i >= StorageVolumeDeleteFlags(len(_StorageVolumeDeleteFlags_index)-1) {
		return fmt.Sprintf("StorageVolumeDeleteFlags(%d)", i)
	}
	return _StorageVolumeDeleteFlags_name[_StorageVolumeDeleteFlags_index[i]:_StorageVolumeDeleteFlags_index[i+1]]
}

const (
	_StorageVolumeResizeFlags_name_0 = "StorageVolumeResizeFlagNoneStorageVolumeResizeFlagAllocate"
	_StorageVolumeResizeFlags_name_1 = "StorageVolumeResizeFlagDelta"
	_StorageVolumeResizeFlags_name_2 = "StorageVolumeResizeFlagShrink"
)

var (
	_StorageVolumeResizeFlags_index_0 = [...]uint8{0, 27, 58}
	_StorageVolumeResizeFlags_index_1 = [...]uint8{0, 28}
	_StorageVolumeResizeFlags_index_2 = [...]uint8{0, 29}
)

func (i StorageVolumeResizeFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _StorageVolumeResizeFlags_name_0[_StorageVolumeResizeFlags_index_0[i]:_StorageVolumeResizeFlags_index_0[i+1]]
	case i == 4:
		return _StorageVolumeResizeFlags_name_1
	case i == 8:
		return _StorageVolumeResizeFlags_name_2
	default:
		return fmt.Sprintf("StorageVolumeResizeFlags(%d)", i)
	}
}

const _StorageVolumeWipeAlgFlags_name = "StorageVolumeWipeAlgZeroStorageVolumeWipeAlgNNSAStorageVolumeWipeAlgDODStorageVolumeWipeAlgBSIStorageVolumeWipeAlgGUTMANNStorageVolumeWipeAlgSCHNEIERStorageVolumeWipeAlgPFITZNER7StorageVolumeWipeAlgPFITZNER33StorageVolumeWipeAlgRandomStorageVolumeWipeAlgTrimStorageVolumeWipeAlgLast"

var _StorageVolumeWipeAlgFlags_index = [...]uint16{0, 24, 48, 71, 94, 121, 149, 178, 208, 234, 258, 282}

func (i StorageVolumeWipeAlgFlags) String() string {
	if i >= StorageVolumeWipeAlgFlags(len(_StorageVolumeWipeAlgFlags_index)-1) {
		return fmt.Sprintf("StorageVolumeWipeAlgFlags(%d)", i)
	}
	return _StorageVolumeWipeAlgFlags_name[_StorageVolumeWipeAlgFlags_index[i]:_StorageVolumeWipeAlgFlags_index[i+1]]
}
